name: Deploy
on:
  push:
    branches: [main]
 
jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: dist/

      - name: Deploy to Orbiter
        uses: orbiterhost/orbiter-github-actions@9efb698e90a7e3acfb64695e41c87a3574bcdf77 #v0.1.8
        with:
          project-name: "jrh3k5.orbiter.website"
          build-dir: "./dist"
          api-key: ${{ secrets.ORBITER_API_KEY }}