name: Deploy
on:
  push:
    branches: [main]
 
jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: dist/

      - name: Deploy to Orbiter
        shell: bash
        env:
          ORBITER_API_KEY: ${{ secrets.ORBITER_API_KEY }}
          SOURCE: github-action
        run: npx orbiter-cli update -d jrh3k5.orbiter.website dist