name: Deploy
on:
  push:
    branches: [main]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
 
      - name: Deploy to Orbiter
        uses: orbiterhost/orbiter-github-actions@9efb698e90a7e3acfb64695e41c87a3574bcdf77 #v0.1.8
        with:
          project-name: "jrh3k5.orbiter.website"
          build-dir: "./"
          api-key: ${{ secrets.ORBITER_API_KEY }}
          skip-install: true # no dependencies to install