name: Deploy
on:
  push:
    branches: [main]
 
jobs:
  validate:
    uses: ./.github/workflows/validate-html.yml

  deploy:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: dist/

      - name: Deploy to Orbiter
        uses: orbiterhost/orbiter-github-actions@v0.1.4 # Update with latest version
        with:
          project-name: "jrh3k5.orbiter.website"
          build-dir: "./dist"
          api-key: ${{ secrets.ORBITER_API_KEY }}
          node-version: "20.x"